// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvzpwjaaitqusledruvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2enB3amFhaXRxdXNsZWRydXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NzI2NTksImV4cCI6MjA2NzM0ODY1OX0.Kt-7tfZeM4lPgGHO0BkZJTAU2vs-znOZxLYSLUYORSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});